### ISSUE TITLE
A new name for the project.

### ISSUE THREAD

**Issue by habetuz** [DHBW-Inf/Toolbox#10]
**Is your feature request related to a problem? Please describe.**
The current name of the project does not reflect the purpose well.

**Describe the changes you would like**
A better suited name is needed. I changed the name of the project to CodingUtils in GitHub now, but this should be discussed before changing the name in code, because this would be a breaking change.

Other naming ideas are welcome.

**Comment by matteokosina** [comment]
> **Is your feature request related to a problem? Please describe.** The current name of the project does not reflect the purpose well.
> 
> **Describe the changes you would like** A better suited name is needed. I changed the name of the project to CodingUtils in GitHub now, but this should be discussed before changing the name in code, because this would be a breaking change.
> 
> Other naming ideas are welcome.

What about Java-Toolbox or something like that? I created a repo for myself a few months ago and called it like that... I also created a little logo for fun :) 


<img width="355"  alt="Screenshot 2024-04-09 at 00 14 00" src="https://github.com/matteokosina/java-toolbox/assets/74454734/5a380b1b-5f20-499b-8dc9-9a481addec81" style="display: block; margin-left: auto; margin-right: auto;">

But I am also fine with other names or just leaving it as is

**Comment by habetuz** [comment]
Like the idea. Should we use `de.toolbox` as package name, to make it more concise?

**Comment by matteokosina** [comment]
Maybe then it would also make sense to just call the repo toolbox wouldn't it?

**Comment by habetuz** [comment]
Yes that should be enough.
