### ISSUE TITLE
Pipeline Update - auto  docs generation

### ISSUE THREAD

**Issue by matteokosina** [DHBW-Inf/Toolbox#6]
**Is your feature request related to a problem? Please describe.**
[N/A]

**Describe the util [feature] you'd like**
Upgrading the Github Pipeline to automatically generate docs.

**Additional context**
For this, the builtin `javadoc` can be used to generate documentation. The result is a simple HTML-Doc.

**Comment by habetuz** [comment]
The documentation should ideally be added to releases either in the same zip as the source code or as additional zip file.

**Comment by matteokosina** [comment]
> The documentation should ideally be added to releases either in the same zip as the source code or as additional zip file.

Should the workflow run with every merge to main trigger or should some be excluded (e.g. chore:... commits)?

**Comment by habetuz** [comment]
Maybe it should be added to the release workflow. Commits labeled as `chore` do not trigger a release. Or do you think the documentation should be updated on `chore` commits to?

**Comment by habetuz** [comment]
Besides publishing the documentation with release it could also be published via GitHub pages (in addition to the release zip file). Do you think that would be beneficial?

**Comment by matteokosina** [comment]
> Maybe it should be added to the release workflow. Commits labeled as `chore` do not trigger a release. Or do you think the documentation should be updated on `chore` commits to?

Depends on the definition of `chore:` I think we are fine with not generating docs when `chore` only applies to maintenance work and no real code changes. :)

**Comment by matteokosina** [comment]
> Besides publishing the documentation with release it could also be published via GitHub pages (in addition to the release zip file). Do you think that would be beneficial?

Yes why not, I can do that as well 👍
